### ISSUE TITLE
Adding Form Customization attributes to Gitify file

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#124]
Hi, I was wondering how I can add MODX Form Customization to my gitify file?  An example would be appreciated!

**Comment by Mark-H** [comment]
If you do `Gitify init` it will offer you to add that to your gitify file, but here you go:

```` yaml
     fc_sets:
        class: modFormCustomizationSet
        primary: id
    fc_profiles:
        class: modFormCustomizationProfile
        primary: id
    fc_profile_usergroups:
        class: modFormCustomizationProfileUserGroup
        primary:
            - usergroup
            - profile
    fc_action_dom:
        class: modActionDom
        primary:
            - set
            - name
````
