### ISSUE TITLE
Install packages doesn't work with MODX 2.4

### ISSUE THREAD

**Issue by renekopcem** [modmore/Gitify#125]
I found out today that the `Gitify install:package --all` doesn't work with the latest MODX 2.4.

It returns:
```
Fatal error: Call to protected method modTransportProvider::getClient() from context 'modmore\Gitify\Command\InstallPackageCommand' in /Users/renekopcem/Gitify/src/Command/InstallPackageCommand.php on line 168
```

To replicate it:
- install MODX `Gitify install:modx`
- add packages to the `.gitify` for example:
```
packages:
    modx.com:
        service_url: 'http://rest.modx.com/extras/'
        description: 'The official MODX transport facility for 3rd party components.'
        packages:
            - ace
            - ckeditor
            - fastfield
            - formit
            - gatewaymanager
            - getcache
            - getresources
            - migx
            - pthumb
            - resizer
            - translit
            - versionx
```

- and run `Gitify install:package --all`

Setup:
OSX, latest Gitify, PHP 5.5.27
