### ISSUE TITLE
Resolving foreign keys

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#13]
I'm thinking that it would be nice if we could provide a better dynamic mechanism for resolving foreign keys. Let's say I store fictional School objects which have ClassRoom objects. Each ClassRoom has a foreign key reference "school" that contains the ID of the School object. 

If the School object has another unique key, for example a string "name", we should be able of using that in the reference from the ClassRoom instead. So if we were to store it like this...

School:

``` yaml
id: 4
name: School ABC
```

ClassRoom:

``` yaml
id: 8
room: #14.12
school: 4
```

I would like to store the ClassRoom like this, instead:

ClassRoom:

``` yaml
id: 8
room: #14.12
school: School ABC
```

I think this would be possible if we add a new option to the .gitify file to indicate what relations to automatically resolve. Something like..

``` yaml
name: test
data_directory: _data
data:
  schools:
    class: School
    primary: name
  classrooms:
    class: ClassRoom
    primary: room
    resolve_relations: [School, OtherRelation]
```

The `resolve_relations` key would contain an array of the relations as defined in the xPDO schema/modal. It would look up the foreign and local keys and do the replacement on both extract and build.
