### ISSUE TITLE
[Question] How to use NOT LIKE condition in where statement

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#138]
I want to exclude keys with a NOT LIKE condition instead of NOT IN, but that doesn't seem to work..

```
    chunks:
        class: modChunk
        primary: name
        where:
            'static_file:NOT LIKE':
                - '[[++patternlab.core_path]]%'
```

Am I doing something wrong, or is this just not possible?

**Comment by Mark-H** [comment]
Should probably be this:

````
    chunks:
        class: modChunk
        primary: name
        where:
            'static_file:NOT LIKE': '[[++patternlab.core_path]]%'
````
