### ISSUE TITLE
Don't install packages from modstore.pro

### ISSUE THREAD

**Issue by Realetive** [modmore/Gitify#186]
### Summary

Catch error on modstore provider section. All is right with modx.com and modmore.com, just with modstore.pro

![2016-05-05 7 27 53](https://cloud.githubusercontent.com/assets/2073959/15036132/8c8d7542-1293-11e6-8136-b40fc36e9640.png)
### Environment

Gitify version: 0.12.0,
MODX version: 2.5.0-pl,
Operating System: Ubuntu 14.04 on Vagrant with PuPHPet,
MySQL version: 15.1 Distrib 10.1.13-MariaDB,
PHP version: 7.0.6-1+donate.sury.org~trusty+1.

**Comment by Realetive** [comment]
Temp fix: specify version for package:
```
  modstore.pro:
    service_url: https://modstore.pro/extras/
    description: Репозиторий дополонений modstore.pro
    credential_file: '../.modstore-pro.key'
    packages:
      - pdotools-2.4.0-pl
      - minishop2-2.4.0-beta1
      - shopstats-1.0.0-beta
      - autoredirector-0.1.0-beta
      - ytranslit-1.2.0-pl
      - debugparser-1.1.0-pl
```

Will stay open this issue at the discretion of @Mark-H.
