### ISSUE TITLE
gitify package:install --all, installing other package(not declared in .gitify)

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [modmore/Gitify#190]
hi all. 
today i try to declare packages in .gitify
in the .gitify i write next
```yaml
packages:
    modx.com:
        service_url: 'http://rest.modx.com/extras/'
        description: 'The official MODX transport facility for 3rd party components.'
        packages:
            - TinyMCE-4.3.3-pl
```
after exec command in console, gitify install simplesearch package
http://prntscr.com/b84e9f
