### ISSUE TITLE
Implement "Environments"

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#32]
Imagine this:
```` 
data:
  content:
    type: content
  chunks:
    class: modChunk
    primary: name
    extension: .html
  users:
    class: modUser
    primary: username
    relations:
      profile: 
        alias: Profile
        class:  modUserProfile
  comments:
    class: QuipReply
    primary: [thread, subject]
    package: quip
environments:
  production:
    build_default: [content, chunks],
    extract_default: [content, users, comments]
  staging
    build_default: [content, users, comments]
    extract_default: [content, chunks]
````

Being able of specifying what happens with the short-hand `Gitify build` without specifying `Gitify build content` (not yet implemented) if you just want the content, depending on the environment (stored in a MODX setting), should help build clever workflows where only part of the extracted objects would need to be build again.
