### ISSUE TITLE
define extras versionnumber in .gifity?

### ISSUE THREAD

**Issue by jenswittmann** [modmore/Gitify#357]
Is it possible to add a versionnumber to the .gitify file? For example:

```
packages:
    modmore.com:
        service_url: https://rest.modmore.com/
        credential_file: '.modmore.com.key'
        packages:
            - 'contentblocks 1.10.0-pl'
            - redactor
```

Now when i run `Gitify package:install contentblocks` i get the version **1.8.15-pl** and not the latest **1.10.0-pl**. Is there something that i miss or is it not possible at the moment?
