### ISSUE TITLE
 PHP warning: Undefined array key "service"

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#426]
### Summary
Extracting with 2.0.0-alpha4 gives this warning in some cases, for example with MoreGallery

```
  moregallery_image:
    class: mgImage
    primary: [resource, id]
    package: moregallery
```

It is possible I just need to update this gitify file, but it would be nice to not get these notices. 

### Step to reproduce

Above snippet in .gitify, run an extract

### Observed behavior

```
[2023-02-17 01:22:14] (ERROR @ vendor/modmore/gitify/src/Command/ExtractCommand.php : 326) PHP warning: Undefined array key "service"
```

### Expected behavior
No warning

### Environment
Gitify 2.0.0-alpha4
MODX 2.8.4
PHP 8.0
