### ISSUE TITLE
Collections 4.0.0-pl not extractable any more

### ISSUE THREAD

**Issue by wuuti** [modmore/Gitify#441]
### Summary
With version 4.0.0-pl of Collections the `model/` folder was removed (it was there in the previous versions?). As a consequence, extracting (and building) of Collections is not possible any more.

### Step to reproduce
- Install Collections 4.0.0-pl extra. 
- Add to `.gitify`:
  ```yml
  collections_settings:
    class: CollectionSetting
    primary: id
    package: collections
  ```

### Observed behavior
Extracting gives error: 
`xPDO.php : 472) Path specified for package collections is not a valid or accessible directory: [snip]/core/components/collections/model`

### Expected behavior
Package data should be loadable even if model folder does not exist (but "src/Model"?). Or is it a Collections bug here, that they stripped the model folder?

I was not able to solve that on my own, e.g. by using `package_path` or `service` in the gitify config... 
A tmp workaround was to just copy the model folder from older versions - but thats clearly not a solution.

### Environment
Gitify version: 2.0.0-alpha4 (not tested yet with current release)
Modx-Version: 3.0.1

**Comment by jenswittmann** [comment]
I have a similar issue with Formalicious.

```
formalicious_fields_types:
        class: FormaliciousFieldType
        primary: id
        package: formalicious
```

Getting this Error with Gitify 2.0.1-pl on MODX 3.0.4:

```
(ERROR @ core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 473) Path specified for package formalicious is not a valid or accessible directory: core/components/formalicious/model/
```

@Mark-H do you have an idea to fix this? #bugbounty
