### ISSUE TITLE
Support relations (aggregate/composite) in a way that makes sense to humans

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#6]
It would be nice to - in a similar way the `content` works - make use of subdirectories to store relations. 

A model mpPackage with one-to-many mpVersion objects could be represented in the `.gitify` like this:

``` yaml
data:
  packages:
    class: mpPackage
    primary: name
    relations: 
       versions:
         class: mpVersion
         alias: Version 
         primary: signature
```

which would then result in a directory structure like this for a one-to-many relation:

```
_data/
  packages/
    redactor.yaml
    redactor/
      versions/
        1.5.0-pl.yaml
```

A one-to-one relation, for example modUser/modUserProfile, could be in the .gitify file like this:

``` yaml
data:
  packages:
    class: modUser
    primary: username
    relations: 
       profile:
         class: modUserProfile
         alias: Profile
```

As it's one-to-one, there would (ideally) be no need to specify a primary. Gitify could fetch that from the model and base it off the modUser record. 

The profile file would be stored with the name from the reference ("profile") in a directory with the primary from the modUser, like so:

```
_data/
  users/
    marksusername.yaml
    marksusername/
      profile.yaml
```

Of course combinations and multiple relations need to be supported.
