### ISSUE TITLE
Issue with modMediaSourceElement

### ISSUE THREAD

**Issue by christianseel** [modmore/Gitify#65]
When adding modMediaSourceElement to .gitify like
```
  mediasources:
    class: modMediaSource
    primary: id
  mediasource_elements:
    class: sources.modMediaSourceElement
    primary: [source, object_class, object, context_key]
```

`Gitify build` shows the following error:

```
2015-03-04 10:45:56 Error 23000 executing statement:
INSERT INTO modx_media_sources_elements (source, object_class, object, context_key) VALUES (1, 'modTemplateVar', 1, 'web')
Array
(
[0] => 23000
[1] => 1062
[2] => Duplicate entry '1-1-modTemplateVar-web' for key 'PRIMARY'
)

Could not save new sources.modMediaSourceElement: {"source":1,"object_class":null,"object":1,"context_key":null}
2015-03-04 10:45:56 Error 23000 executing statement:
INSERT INTO modx_media_sources_elements (source, object_class, object, context_key) VALUES (2, 'modTemplateVar', 2, 'web')
Array
(
[0] => 23000
[1] => 1062
[2] => Duplicate entry '2-2-modTemplateVar-web' for key 'PRIMARY'
)

Could not save new sources.modMediaSourceElement: {"source":2,"object_class":null,"object":2,"context_key":null}
```
