### ISSUE TITLE
config.inc.php remains empty after install:modx

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#70]
Tried several times with different settings.. Install seems to be running just fine:

`Done! Time: 251,100ms | Memory Usage: 1.97 mb | Peak Memory Usage: 2 mb`

..but this is in my config.inc.php:

`<?php // MODX configuration file ?>`

I'm on latest OSX and latest Gitify build (although it says 0.5.1, but that's because version nr didn't get updated on latest). This is in my Gitify file:

```
data_directory: _data/
data:
    contexts:
        class: modContext
        primary: key
    context_settings:
        class: modContextSetting
        primary: [context_key, key]
        exclude_keys:
          - editedon
    content:
        type: content
        exclude_keys:
          - editedby
          - editedon
    categories:
        class: modCategory
        primary: category
    templates:
        class: modTemplate
        primary: templatename
    template_variables:
        class: modTemplateVar
        primary: name
    template_variables_access:
        class: modTemplateVarTemplate
        primary: [tmplvarid, templateid]
    chunks:
        class: modChunk
        primary: name
    snippets:
        class: modSnippet
        primary: name
        extension: .php
    plugins:
        class: modPlugin
        primary: name
        extension: .php
    plugin_events:
        class: modPluginEvent
        primary: [pluginid,event]
    events:
        class: modEvent
        primary: name
    namespaces:
        class: modNamespace
        primary: name
    extension_packages:
        class: modExtensionPackage
        primary: namespace
    system_settings:
        class: modSystemSetting
        primary: key
        exclude_keys:
          - editedon
    access_policies:
        class: modAccessPolicy
        primary: name
    fc_profiles:
        class: modFormCustomizationProfile
        primary: name
    fc_profiles_usergroups:
        class: modFormCustomizationProfileUserGroup
        primary: [usergroup, profile]
    fc_sets:
        class: modFormCustomizationSet
        primary: profile
    #ContentBlocks
    cb_fields:
        class: cbField
        primary: name
        package: contentblocks
    cb_layouts:
        class: cbLayout
        primary: name
    cb_templates:
        class: cbTemplate
        primary: name
    cb_defaults:
        class: cbDefault
        primary: constraint_field
    #clientConfig
    cg_groups:
        class: cgGroup
        primary: label
        package: clientconfig
    cg_settings:
        class: cgSetting
        primary: key
    #Collections
    collections_settings:
        class: CollectionSetting
        primary: collection
        package: collections
    collections_templates:
        class: CollectionTemplate
        primary: name
    collections_template_columns:
        class: CollectionTemplateColumn
        primary: template
    collections_resource_templates:
        class: CollectionResourceTemplate
        primary: [collection_template, resource_template]
    collections_selections:
        class: CollectionSelection
        primary: collection
    #QuickStartButtons
    qsb_buttons:
        class: qsbButton
        primary: set
        package: quickstartbuttons
    qsb_icons:
        class: qsbIcon
        primary: name
    qsb_sets:
        class: qsbSet
        primary: name
    qsb_usergroups:
        class: qsbSetUserGroup
        primary: [usergroup, set]
    # #SEOPro
    # sp_keywords:
    #     class: seoKeywords
    #     primary: resource
    #     package: seopro
    #Tagger
    tagger_groups:
        class: TaggerGroup
        primary: name
        package: tagger
    tagger_tags:
        class: TaggerTag
        primary: tag
    tagger_tag_resources:
        class: TaggerTagResource
        primary: [tag, resource]
packages:
    modx.com:
        service_url: http://rest.modx.com/extras/
        packages:
            - Ace
            - BigBrother
            - BreadCrumb
            - Collections
            - fastField
            - formit
            - getPage
            - getResources
            - Hits
            - pThumb
            - resizer
            - Rowboat
            - SEOPro
            - SimpleSearch
            - Tagger
            - UltimateParent
            - Wayfinder
    modmore.com:
        service_url: https://rest.modmore.com/
        username: hugopeek_gitify_dev2
        api_key: modmore.com.key
        packages:
            - clientConfig
            - contentblocks
            - QuickstartButtons
            - Redactor
```
