### ISSUE TITLE
install:package for some packages not working

### ISSUE THREAD

**Issue by christianseel** [modmore/Gitify#74]
The "is installed?" check seems to return a wrong `false` for those packages:
- faqman
- gridclasskey
- seotab
- seopro

…they are installed but Gitify tries to install them again and you end up with `Duplicate entry 'faqman-1.1.0-pl' for key 'PRIMARY'` in the `modx_transport_packages` table.

**Comment by christianseel** [comment]
```
packages: 
  modx.com:
    service_url: http://rest.modx.com/extras/
    packages:
      - ace
      - archivist
      - babel
      - breadcrumb
      - clientconfig
      - collections
      - faqman
      - fastfield
      - firstchildredirect
      - formit
      - getcache
      - getpage
      - getresources
      - gridclasskey
      - migx
      - pthumb
      - quip
      - redirectoid
      - seopro
      - seotab
      - simplesearch
      - tagger
      - translit
      - versionx
      - wayfinder
      - xrouting
```
