### ISSUE TITLE
Add template_variables above content in default .yaml

### ISSUE THREAD

**Issue by markwillis82** [modmore/Gitify#88]
After running `gitify init` the template variables are added to the yaml AFTER the content:

```
data:
    contexts:
        class: modContext
        primary: key
    context_settings:
        class: modContextSetting
        primary:
            - context_key
            - key
    content:
        type: content
    categories:
        class: modCategory
        primary: category
        truncate_on_force:
            - modCategoryClosure
    templates:
        class: modTemplate
        primary: templatename
        extension: .html
    template_variables:
        class: modTemplateVar
        primary: name
    template_variables_access:
        class: modTemplateVarTemplate
        primary:
            - tmplvarid
            - templateid
```

This causes an issue when importing data into a clean modx because the TVs don't exist when the content is added (so they all go in blank). The template_variables need to be added to the YAML above the content
