### ISSUE TITLE
build+extract results in file/ID changes with MIGX

### ISSUE THREAD

**Issue by christianseel** [modmore/Gitify#90]
Gitify version 0.8 + 0.9.

my .gitify:
```
  migx_config:
    class: migxConfig
    primary: id
    package: migx
  migx_formtab:
    class: migxFormtab
    primary: id
  migx_formtab_field:
    class: migxFormtabField
    primary: id
  migx_config_element:
    class: migxConfigElement
    primary: id
  migx_element:
    class: migxElement
    primary: id
```

…when I buid + extract afterwards I always end up with changed IDs in my `_gitify/migx_config/*` files.

![voila_capture 2015-05-18_03-20-25_nachm](https://cloud.githubusercontent.com/assets/482184/7681559/6c2f443e-fd71-11e4-88db-35e7a93a4fef.png)

(the `MIGX_id` of the `formtabs` always gets an increment…)

**Comment by Mark-H** [comment]
Here's the bugger: https://github.com/Bruno17/MIGX/blob/master/core/components/migx/model/migx/migxformtab.class.php#L26

**Comment by christianseel** [comment]
changing the order of the MIGX objects in my `.gitify` file did the trick!

it now looks like
```
  migx_formtab:
    class: migxFormtab
    primary: id
    package: migx
  migx_formtab_field:
    class: migxFormtabField
    primary: id
  migx_config_element:
    class: migxConfigElement
    primary: id
  migx_element:
    class: migxElement
    primary: id
  migx_config:
    class: migxConfig
    primary: id
```

…just placed the migx_config at the bottom. Gitify now corectly handles the formtabs.
